Feature/175 user/verify account
Make-A-Wish-Sopt/Make-A-Wish-Client pull request #180
Opened 2023-12-29 14:58 UTC by Me1e

## 이슈 넘버

- close #175 

## 구현 사항

- [x] /wishes의 "계좌번호 입력하기" 섹션에 필요한 모든 기능 구현
- [x] UX 고려하여 input & button에 disable 효과 추가

## Need Review

정확히 "계좌 인증" 로직만 추가했습니다. 앞뒤로 어떤 컨텍스트가 있는지 잘 파악이 안돼서요.. 그 부분을 중점으로 에러 사항 확인해주심 감사하겠습니다.

## 📸 스크린샷

## Reference

2024-01-02 02:25 UTC, myeongheonhong requested changes
리팩토링이라 썼지만 코드 이해하시기가 어려우셨을 텐데 잘 구현해주셔서 감사합니다!
해당 리뷰만 수정하면 바로 병합해도 좋을거 같습니다!

2024-01-02 02:25 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +      methods.watch('account') !== '' &&
이 부분은 저도 급하게 입력 처리를 한것도 있고, 리액트 훅폼을 제대로 공부를 미쳐 못했던 부분이 있어서 이렇게 코드를 작성했는데, 코드를 작성하면서도 이렇게 코드를 짜면 리액트 훅폼의 장점을 전혀 못살리는거 같더라구요...!! 

조금더 공부를 해보니 useForm에서 mode를 onChange로 주게되면 해당 조건들을 실시간으로 파악해서 isValid라는 변수에 boolean값으로 들어오더라구요!! 

제가 맡은 부분도 수정할 예정이라서 해당 아티클 참고하셔서 적용해주시면 감사하겠습니다!!!

https://velog.io/@kihyun/React-Hook-Form-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0#%EC%8B%A4%EC%8B%9C%EA%B0%84-%EC%9C%A0%ED%9A%A8%EC%84%B1-%EA%B2%80%EC%82%AC

2024-01-02 02:25 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +          disabled={isSuccess || isAbused}
disabled 조건을 모든 입력창에 넣어주셨는데 
예를들어 계좌인증에 성공을 하고 다른 계좌가 생각나서 변경해야할 경우에는 해당 조건이 불편할거 같다는 생각이들어요! 
피그마 디자인에도 버튼만 비활성화 되는것처럼 나오는데 이부분은 체크해서 변경해주셔야 될거 같습니다!

2024-01-02 02:25 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +            className={!btnState ? 'gray1_white' : 'mainBlue_white'}
위에서 언급드린 리액트 훅폼 실시간 유효성 검사를 통하게 된다면 btnState라는 변수가 굳이 필요하지 않을거 같다는 생각이 들기도 하네요!! 불필요한 변수를 줄여나가는것도 최적화에 도움이 된다고 생각하는데 어떻게 생각하시나요?!

2024-01-02 02:25 UTC, myeongheonhong commented on hooks/queries/user.ts
> +   */
별건 아니지만 이렇게 주석을 친절하게 달아주셔서 동작에 대해 이해하기가 훨씬 잘되는거 같네요!!
저도 주석을 잘 활용해보는 방향으로 코딩을 해야겠네요!! 하나 배워갑니다!! 감사해요!!

2024-01-03 07:35 UTC, Me1e commented on components/Common/Modal/BankInput.tsx
> +      methods.watch('account') !== '' &&
UseFrom 객체가 상위 컴포넌트에서 내려오고 있는데, 동시에 수정하게 되지는 않을까요?!

2024-01-03 07:50 UTC, Me1e commented on components/Common/Modal/BankInput.tsx
> +          disabled={isSuccess || isAbused}
지금 구조에선
1. 계좌 인증 후
2. 계좌 관련 내용 수정 하고
3. 계좌 인증은 추가로 안 하고
4. 링크 생성 하기 누르면
"인증 안 된 계좌 관련 내용"으로 소원이 생성되지 않을까 해서 disable 해뒀어요!!
문제되지 않는건가요?!?

2024-01-03 07:55 UTC, Me1e commented on components/Common/Modal/BankInput.tsx
> +            className={!btnState ? 'gray1_white' : 'mainBlue_white'}
버튼 비활성 기능을 제거하자는 의견이신건가요?!

인증 성공 후 "계좌번호 확인" 버튼을 계속 누를 수 있게 해두면, 불필요한 비용이 나갈 것 같아서 변수로 disable을 관리했어요!

2024-01-03 07:56 UTC, Me1e commented on hooks/queries/user.ts
> +   */
외부 api가 예상하기 어려운 동작 방식이면 써두곤 했습니다!! 감사합니다 :)

2024-01-03 07:56 UTC, Me1e commented on hooks/queries/user.ts
> +   */
사실 api 문서에 있어야 하는 내용이긴 하다만..

2024-01-03 10:11 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +      methods.watch('account') !== '' &&
음 지금 생각해보니 상위 컴포넌트에서 useForm객체를 전달해주어서 isValid는 맞지 않는거 같네요..!!!

watch를 통해 조건을 처리해도 크게 상관은 없지만 react-hook-form에서 제공하는 유효성검사로 (ex. setError,errors)체크를 하는게 좋을거 같다는 생각이 드네요! 그렇게 되면 동시에 useForm을 사용하면서 문제되지는 않을거 같습니다!

2024-01-03 10:22 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +          disabled={isSuccess || isAbused}
문제...가 되지는 않긴한데.. 만약 계좌인증을 하고 다른 계좌로 바꿔야하는 상황이라면 이전으로 돌아갔다가 현재 스텝으로 돌아오는 리소스가 필요할거 같아요..!!

그래서 다음스텝으로 넘어가는 버튼액션 활성화조건과, 계좌인증 버튼 조건을 추가해야할거 같다는 생각이 드는데 어떻게 생각하시나요!?!
예를들면 계좌 인증 성공 시 계좌번호를 저장하고 계좌번호를 지우거나 추가됐을때 계좌인증버튼을 다시 활성화 하고, 다음으로 넘어가는 버튼은 비활성화하는 그런 방법으로요!

[ 유저 케이스 ]
1. 1234 계좌 인증 성공시 - '계좌번호확인'버튼(회색 : 비활성화) / '링크생성완료'(파란색 : 활성화)
2. 123으로 계좌 변경시 - '계좌번호확인'버튼(파란색 : 활성화) /  '링크생성완료'(회색 : 비활성화)

2024-01-03 10:26 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +            className={!btnState ? 'gray1_white' : 'mainBlue_white'}
버튼 비활성 기능을 제거하는건 아닌데 변수를 하나 추가해서 관리하는거에 대해서 어떻게 생각하시는지 여쭤봤습니다! 
위에서 언급드린 레지스터 유효성검사를 통해서도 조건판단이 가능할거 같다는 생각이들어서 언급을 드렸습니다!!!
코드가 지저분해질 수도 있다는 단점이 있기도 해서 민준님의 코드대로 btnState를 통해 버튼상태를 변경하는것도 좋은 거 같네요!!

2024-01-04 11:04 UTC, Me1e commented on components/Common/Modal/BankInput.tsx
> +      methods.watch('account') !== '' &&
전역에서 사용되고 있는 useForm 객체의 mode를 onChange로 수정하지 않는 선에서 react-hook-form 기능으로 실시간 유효성을 체크해보려는데, 마땅한 방법이 생각나지 않네요 ㅠㅠ
어떤 방법들이 있을까요?

2024-01-04 11:21 UTC, Me1e commented on components/Common/Modal/BankInput.tsx
> +          disabled={isSuccess || isAbused}
기존 구조가
```js
if (
  checkBoxState &&
  methods.getValues('name') &&
  methods.getValues('bank') &&
  methods.getValues('account') &&
  methods.getValues('phone') &&
  validation.isCorrectPhoneNumber(methods.getValues('phone'))
) {
  wishesStep.changeNextState(true);
} else {
  wishesStep.changeNextState(false);
}
```
field에 내용만 들어가 있으면 next 버튼에 불이 들어오는 상황이라, 더 좋은 방향으로 개선하려면 수정이 많이 일어날 것 같아요!
진행할까요??

2024-01-06 14:16 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +      methods.watch('account') !== '' &&
아 아닙니다! mode를 수정하지 않는 선에서는 watch를 통한 유효성 검사를 해야할 거 같습니다!!
주어진 기간에는 꽤나 분량이 있는 리팩토링이라 생각되어 나중에 다시한번 체크해보는걸로 해요!!ㅎㅎ

2024-01-06 14:17 UTC, myeongheonhong commented on components/Common/Modal/BankInput.tsx
> +          disabled={isSuccess || isAbused}
아하... 들어가는 리소스도 무시하지 못하니... 이 부분은 나중에 위에서 실시간 유효성 검사가 가능하게 될때에 다시한번 점검을 해봐야할거 같습니다!

2024-01-08 07:47 UTC, merged